### ISSUE TITLE
Clint Barton Hawkeye card duplicated and missing subname

### ISSUE THREAD

**Issue by SwedeRacer** [zzorba/marvelsdb-json-data#265]
There are two copies of the Clint Barton Hawkeye card (Ids 01066 and 03012). Also, neither version of this card includes the subname "Clint Barton".

**Comment by funkymonkeymonk** [comment]
03012 is a duplicate and should be as Hawkeye was included in the Captain America set. This looks to be handled the same way that other duplicates are. One of the Maintainers can correct me if I'm wrong here. I'm putting up a PR to include the subname on 01066.

**Comment by funkymonkeymonk** [comment]
PR is up: https://github.com/zzorba/marvelsdb-json-data/pull/273

**Comment by funkymonkeymonk** [comment]
PR was merged. Can this be closed?

**Comment by SwedeRacer** [comment]
There are still two instances of this card in the database, but they both have the correct subname now, which was the main issue, so I'll close it.
