### ISSUE TITLE
Wrong images for three Valkyrie cards

### ISSUE THREAD

**Issue by TomasLoow** [zzorba/marvelsdb-json-data#285]
As can be seen from this link

https://marvelcdb.com/set/valk/card/all/set/2

The cards with 25027, 25028 and 25029 show the wrong images.

![image](https://user-images.githubusercontent.com/12694374/183402723-d320a88f-4d40-421e-a26f-479fd83c14e7.png)

**Comment by dimitrisnl** [comment]
Opened the same ticket here https://github.com/zzorba/marvelsdb/issues/157 

Seems to be an issue with the ids. They are 1 digit different to the Ghost spider ones.
