### ISSUE TITLE
X-Men Alt art duplicates

### ISSUE THREAD

**Issue by fafranco82** [zzorba/marvelsdb-json-data#286]
This is more a question than an issue... But, Did you think something about x-men duplicates with alt art (and flavor text)? Should I use the "duplicate_of" attribute as with other duplicates or instead treat them like they were new cards?

**Comment by Kamalisk** [comment]
duplicates as normal. They end up with their own card code and can have specific art on their pages, just are treated as one card in the deck builder.

**Comment by fafranco82** [comment]
Perfect! Thanks!
