### ISSUE TITLE
In Fr translation vnm_encounter is not a jsonFile

### ISSUE THREAD

**Issue by clementvp** [zzorba/marvelsdb-json-data#290]
Hello and thank you for this awesome project.

I noticed that in fr translation the file called vnm_encounter is not a properly named json file ( missing .json extension).

PR for this is [HERE](https://github.com/zzorba/marvelsdb-json-data/pull/291)

**Comment by SlyMCFr** [comment]
I fixed it (Pull Request #292)

**Comment by clementvp** [comment]
Awesome.
