### ISSUE TITLE
[FR] Some Typos on FR translations

### ISSUE THREAD

**Issue by clementvp** [zzorba/marvelsdb-json-data#295]
Hi.

There are some Typos on FR Translations:  

Card code number 06005  -> traits change "ataque" to "attaque".  
Card code number 07049 -> traits change "armor" to "armure".
Card code number 06019 -> traits change "arma" to "arme".  ( Already mark by @SlyMCFr )
Card code number 18026 -> traits change "elite" to "élite" ( To be consistent with others).

Maybe @SlyMCFr  can Open PR, Or I can too if you want. I'm available to contribute to this project for FR translations :)

**Comment by SlyMCFr** [comment]
All traits fixed.
