### ISSUE TITLE
[FR] Spider Ham Alter ego

### ISSUE THREAD

**Issue by clementvp** [zzorba/marvelsdb-json-data#303]
In FR Spider Ham alter ego is flagged as "sp//dr armor".  
See : 
![Capture](https://user-images.githubusercontent.com/11894024/191337415-1c7565b6-9e23-483e-a54e-c15a1e586bf9.PNG)
 I think this is an Issue for the greatest @SlyMCFr

**Comment by SlyMCFr** [comment]
arf .... new mistake for me.
SP//dr fixed a second time in Pull Request #302 

So, I apologize for all the mistakes in the last packs ... I'm gonna very soon change and improve my checklist before commits in order to be better with incoming packs ...
