### ISSUE TITLE
[Wave 6 + Mojo] Cards code Vs FFG's code

### ISSUE THREAD

**Issue by SlyMCFr** [zzorba/marvelsdb-json-data#318]
Hi,

I saw in packs.json that mojo, wolverine and stom have been preconfigured : Mojo is marked a "35", Wolverine "36" and Storm "37".
But, if you check on FFG web site, Mojo is referenced as "MC39en", Wolverine "MC35en" and Storm "MC36en".

I thought it could generate troubles in future json files.   
(Same things for incoming Gambit (38 here but MC37en on FFG) and Rogue (39 here Vs MC38en on FFG). )

So, don't you think it could be better keeping the FFG's code for all these packs ?

**Comment by Kamalisk** [comment]
I think you or someone updated them already, but the cdgb_id in the pack file can be changed whenever, they were set up for automatic import (which no longer works since the data is not added to cgdb anymore)
