### ISSUE TITLE
Dr. Strange Invocation deck

### ISSUE THREAD

**Issue by lostie** [zzorba/marvelsdb-json-data#34]
Even though the Invocation deck cards are added to the JSON data, we still require some sort of configuration to set them as part as the default build for Dr. Strange. I was trying to look into the ArkhamDB to understand how that is achieved for Joe Diamond that has a similar requirement.

Any ideas on how this can be enabled? /cc @zzorba @Kamalisk

**Comment by Kamalisk** [comment]
its a bit different for Strange as they are not part of his deck at all. Currently extra cards like obligations and such don't show up in the deck lists.
