### ISSUE TITLE
Missing text on several Mutant Genesis encounter cards

### ISSUE THREAD

**Issue by jordanweiler** [zzorba/marvelsdb-json-data#381]
A lot of the Mutant Genesis encounter cards have missing text

**Comment by funkymonkeymonk** [comment]
Is there a reason that for the MG double sided cards the double_sided filed got dropped?

**Comment by mmougy** [comment]
This should fix main scheme double side cards
https://github.com/zzorba/marvelsdb-json-data/pull/455
