### ISSUE TITLE
Domino ally text not displayed

### ISSUE THREAD

**Issue by mmougy** [zzorba/marvelsdb-json-data#430]
the "attack_text" seems to not work with allies:

on the Domino ally, the following should be displayed, but is not:
"attack_text": "<b>Response</b>: After you use one of Domino's basic powers, swap a card in your hand with the top card of your deck.",

![image](https://github.com/zzorba/marvelsdb-json-data/assets/141938567/0b6b2267-044f-401c-8045-bfebc4f11d0d)

Currently Havok is well displayed, but using "text" instead of "attack_text"
"text": "[star] <b>Forced Interrupt</b>: When Havok attacks, discard the top card of the encounter deck.

![image](https://github.com/zzorba/marvelsdb-json-data/assets/141938567/efc4c8dd-434a-4512-ac17-c77331aee9db)

**Comment by mmougy** [comment]
@jordanweiler 
is the support of "attack_text" for allies is an incoming feature?

**Comment by jordanweiler** [comment]
Good question. I actually made the changes with the new NeXt Evolution heroes thinking that would be the case. I even coded https://github.com/zzorba/marvelsdb/pull/207 to add that support on the server side. After talking with Kamalisk, it was decided to just use `text` for card text and if we need to showcase a star symbol next to the attack/thwart/etc fields, we can add that as a new separate property on cards.

What that means is that any existing ally cards that use `attack_text` or `thwart_text` should change to be `text` and we'll need to add new (they don't exist yet) fields for `attack_star` and `thwart_star` to showcase the star symbol.

I'll try to come back and update the new packs I added to have this change and I'm planning on working on the larger change to add support for the `{field}_star` properties on the backend.

**Comment by mmougy** [comment]
> What that means is that any existing ally cards that use `attack_text` or `thwart_text` should change to be `text` and we'll need to add new (they don't exist yet) fields for `attack_star` and `thwart_star` to showcase the star symbol.

I can help on this change

https://github.com/zzorba/marvelsdb-json-data/pull/431
