### ISSUE TITLE
Link of [Go to card page] loses the current locale

### ISSUE THREAD

**Issue by lucasvc** [zzorba/marvelsdb-json-data#490]
When viewing a deck in any non-english locale (URL starts with the locale code: `es`, `it`,...), card names are view correctly.
![Example deck](https://github.com/zzorba/marvelsdb-json-data/assets/1053448/1e31630a-f5cb-4b05-a67c-437428f71182)
On clicking on it the "preview" is displayed in the same locale.
![Example card preview](https://github.com/zzorba/marvelsdb-json-data/assets/1053448/106bc7d5-acf1-4765-942f-443a3d259fb2)
But the button below [Go to card page] rendered with the URL without locale, so text is displayed in english.
![Link URL for the given card, without locale](https://github.com/zzorba/marvelsdb-json-data/assets/1053448/5e3c5079-0bd2-4038-a6ff-7dae6baa2542)
![Card page in english](https://github.com/zzorba/marvelsdb-json-data/assets/1053448/12a39f6a-772f-4540-8c3c-547d9b48d004)

I recall that a few months ago, going to that card also was being seen in the current locale.
Is this change expected new behaviour? It is a little bit weird and uncomfortable to keep changing language when viewing cards from deck this way.
This happens in any browser.
Checked with other users.

Thanks.

**Comment by lucasvc** [comment]
Description links are rendered with the correct locale URL.

**Comment by Kamalisk** [comment]
its because of the static generation of the card data. it should behave sensibly again now.
