### ISSUE TITLE
amplification icon

### ISSUE THREAD

**Issue by mmougy** [zzorba/marvelsdb-json-data#528]
there are 2 different descriptors for the same concept: amplification icon (<img src="https://github.com/user-attachments/assets/3498f759-8e2e-45fc-950a-a25011c0ce2d" width="30px"/>)

 - scheme_amplify
 - scheme_boost

both seems not supported:

![image](https://github.com/user-attachments/assets/98217035-5353-4198-98fa-0a3060a9dcbf)

![image](https://github.com/user-attachments/assets/0d42124a-c9b8-4469-8507-c83732ad7855)

<br /><br /><br />

![image](https://github.com/user-attachments/assets/976d3aba-5b0b-4718-8380-d3e590901052)

![image](https://github.com/user-attachments/assets/e1d9e608-4cc4-4114-aae8-671daf0990e7)

What is the strategy to display the amplify icon?

**Comment by jordanweiler** [comment]
I created https://github.com/zzorba/marvelsdb/issues/250 for this issue. The backend doesn't support these fields yet but I've been actively coding the JSON against `scheme_amplify` for a while now so most of the newer cards that display this icon should be ready to work once the backend is updated. `scheme_boost` seems like an overloaded term with the other boost fields we already have and doesn't seem like a good name. The official icon is called `amplify` from the official rules.

**Comment by jordanweiler** [comment]
Yes, any previous `scheme_boost` properties should be replaced by `scheme_amplify` once the feature is implemented on the backend.

FYI, `scheme_amplify` should be used for the card property but if it's within text we should use `[amplify]` just like we use `[acceleration]`, `[crisis]`, or `[hazard]` to display the icon within text.
