### ISSUE TITLE
Spider-Woman Aspect Cards

### ISSUE THREAD

**Issue by wargfn** [zzorba/marvelsdb-json-data#66]
Spider-Woman's Kit cards are showing as Aspects when deck-building instead of kit cards.

**Comment by Kamalisk** [comment]
they shouldnt show up in the card list, but they should show up in her decklist as aspect cards (because they are).

**Comment by wargfn** [comment]
Everyone elses kit shows up with the Person icon. they should have that and be colored accordingly if Aspect colors need to be shown. It is confusing to see so many aspect cards and not 15 Identity cards.
